### ISSUE TITLE
Mask Detection

### ISSUE THREAD

**Issue by dangk4atwit** [dangk4atwit/dangk4atwit.github.io#10]

**Comment by hoj2atwit** [comment]
[removed place holder verify content and added real mask and symptom p…](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/71ab8fd96cb432ba673a7b1b469b5fa7c7f522ca)

**Comment by hoj2atwit** [comment]
[some new mask progress, still have an error](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/9bd3d9b104bd6d0c62b4431672fcf9fe6ee3fa4f)

**Comment by hoj2atwit** [comment]
[this should be what i need to work, but gpu error](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/94c089a812666dc0246ab65b709e3059b98033d7)

**Comment by hoj2atwit** [comment]
[complie for tensorflow](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/3414237498010d4acf73e81d6c176c80fd1c7644)

**Comment by hoj2atwit** [comment]
[fixed still camera](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/5516816c5812daa79e1104b3e97da674cab73fa3)

**Comment by hoj2atwit** [comment]
[connected mask detection with verification](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/1c078c8c4467ca79fbe16a4ce1a5a28bf9955954)
