### ISSUE TITLE
Organization Edit Features

### ISSUE THREAD

**Issue by hoj2atwit** [dangk4atwit/dangk4atwit.github.io#18]

**Comment by nguyent63atwit** [comment]
[clean up](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/356562b446be8d6ea9b84e8be2ccda5174c6c861)

**Comment by hoj2atwit** [comment]
[setup nav bar to pull from organization settings](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/43810992e55244f9abecb45d79bdcb171ccf1ef1)

**Comment by hoj2atwit** [comment]
[fixed admin check and made subnavbar for verify menus](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/9bf0c95c61c7ceea06e15ac50d02a306a6ffc7bc)

**Comment by hoj2atwit** [comment]
[added support for subnav in hamburger menu](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/61c44b3e5012409b667b93eaf215eed08f5fc784)

**Comment by hoj2atwit** [comment]
[removed place holder verify content and added real mask and symptom p…](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/71ab8fd96cb432ba673a7b1b469b5fa7c7f522ca)

**Comment by hoj2atwit** [comment]
[added basic css to org_management page](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/4375b1e3f3b193d067ac657a09d571fef33c112e)

**Comment by hoj2atwit** [comment]
[created config for organization and fixed nav bar active for subnav](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/a51fc110c3ca4f8f43a1abb008c45201d56fbed9)

**Comment by hoj2atwit** [comment]
[organization feature customization now works properly.](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/c5f718fde4b791361799af9859d2db367c00a4bb)

**Comment by hoj2atwit** [comment]
[stylized org customization menu](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/3e01f617f3c056b580a1e3f751fef831e13c0a01)
