### ISSUE TITLE
Login UI

### ISSUE THREAD

**Issue by dangk4atwit** [dangk4atwit/dangk4atwit.github.io#2]

**Comment by hoj2atwit** [comment]
Login page created, but not fully functional.

**Comment by hoj2atwit** [comment]
a31f1ed173e971ec9ae4bb6873e7c8c906a8577f

**Comment by hoj2atwit** [comment]
a6be3d7bab70553b097a83be085da5ac49f84b95
New Background on Login

**Comment by hoj2atwit** [comment]
8c6bdb26232cbda653dd24add1c90a674197e8c5

**Comment by hoj2atwit** [comment]
bb317e24ca17333c6efa97811c985d6bb69cd4fc - Restructured to use WTForms
