### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by dangk4atwit** [dangk4atwit/dangk4atwit.github.io#3]

**Comment by hoj2atwit** [comment]
[Camera Working!](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/fec6388454465af59f5ebdf8f869ffcb4365278b)

**Comment by hoj2atwit** [comment]
[fixed centering on camera](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/fdc6c02619520c4d7f2b4963ec1706d4b93167d7)
