### ISSUE TITLE
Time Card

### ISSUE THREAD

**Issue by dangk4atwit** [dangk4atwit/dangk4atwit.github.io#4]

**Comment by hoj2atwit** [comment]
eb23447d62f05723e266e304e9424d862f7ca648

**Comment by hoj2atwit** [comment]
d240a49de10d485f18d2fe7bf6fb20c6c0dd3a62

**Comment by nguyent63atwit** [comment]
358fe7f6bc75d53642af3bef59a897672d100307 - created test modal for timecard, but doesnt submit properly

**Comment by hoj2atwit** [comment]
[made modal connect with main timecard. No database to save it to though.](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/f0b3d88865935849cc62bcbb5730c4485853f4e6)

**Comment by hoj2atwit** [comment]
[implemented above 24hour check for inputing timecard hours.](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/0459e17fb65ae514d5e541b91edec2fc37b3a082)

**Comment by hoj2atwit** [comment]
[redirects from modal if no previous timecard element was selected.](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/2459045f45e51ea1f5f70b397e007e8ceb9f662d)

**Comment by hoj2atwit** [comment]
[time db](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/c2d9d1f7911042d769f2517b4bf679fd16340171)

**Comment by hoj2atwit** [comment]
[Timecard can now load from database and save to database. Can also su](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/63c6465068cdcce7a2ee86a3ddca465510d06089)

**Comment by hoj2atwit** [comment]
[displays total hours worked in timecard](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/1d0d0601b0431fda628bf8f14eef1da5e87bff78)

**Comment by nguyent63atwit** [comment]
[removed timecard feature from people who arent payed weekly](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/e2f92766c71184aedb8cc85723a4499b32e26513)
