### ISSUE TITLE
Symptom Checker

### ISSUE THREAD

**Issue by dangk4atwit** [dangk4atwit/dangk4atwit.github.io#5]

**Comment by hoj2atwit** [comment]
[removed place holder verify content and added real mask and symptom p…](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/71ab8fd96cb432ba673a7b1b469b5fa7c7f522ca)

**Comment by hoj2atwit** [comment]
[Symptom Checker Now Functional](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/8cdd15ee59b4f49424a70e2b14c392e64e18341e)
