### ISSUE TITLE
Clock Out

### ISSUE THREAD

**Issue by dangk4atwit** [dangk4atwit/dangk4atwit.github.io#7]

**Comment by hoj2atwit** [comment]
[Clock in database created](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/4ffb083e37937b538c503d44240194373aca6d77)

**Comment by hoj2atwit** [comment]
[Clock in button works (isn't pretty though)](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/8e9c5c84cd1fb79558c8f6e9b76d7e51f6d72df2)

**Comment by hoj2atwit** [comment]
[Made clockout add to current time in timecard and displays last clock…](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/c7a83bb72cc68ed513ba48f109f8d6a3724fa39d)
