### ISSUE TITLE
Positive Case

### ISSUE THREAD

**Issue by dangk4atwit** [dangk4atwit/dangk4atwit.github.io#9]

**Comment by hoj2atwit** [comment]
[removed place holder verify content and added real mask and symptom p…](https://github.com/dangk4atwit/dangk4atwit.github.io/commit/71ab8fd96cb432ba673a7b1b469b5fa7c7f522ca)

**Comment by hoj2atwit** [comment]
Pretty sure this was replaced by
https://github.com/dangk4atwit/dangk4atwit.github.io/projects/2#card-84464693
